name: Check Updates

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'

env:
  VERSION_FILE: black_version.txt

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Check Updates
      run: |
        # Get the latest version of Black
        NEWSET_VERSION=$(curl -s https://pypi.org/pypi/black/json | jq -r '.info.version')
        echo NEWSET_VERSION=$NEWSET_VERSION
        # Get the current version in the repo
        CURRENT_VERSION=$(cat $VERSION_FILE)
        echo CURRENT_VERSION=$CURRENT_VERSION
        [ "$NEWSET_VERSION" == "$CURRENT_VERSION" ] && echo "Nothing to update" && exit 0
        # Update the current version
        echo "$NEWSET_VERSION" > $VERSION_FILE

        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git config --global push.followTags true
        git commit -m "bump version to $NEWSET_VERSION" -a
        git tag -a $NEWSET_VERSION -m "black version $NEWSET_VERSION"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
